language: node_js
node_js:
  - "8"
install: 
  - npm i
  - npm i -g parcel-bundler 
script: npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  local-dir: ./dist
  on:
    branch: master